sudo: required
services:
  - docker

before_install:
  - docker build -t luckytintinnz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true luckytintinnz/react-test npm test

after_success:
  - docker build -t luckytintinnz/multi-client ./client
  - docker build -t luckytintinnz/multi-nginx ./nginx
  - docker build -t luckytintinnz/multi-server ./server
  - docker build -t luckytintinnz/multi-worker ./worker
  # Login to docker-cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker hub
  - docker push luckytintinnz/multi-client
  - docker push luckytintinnz/multi-nginx
  - docker push luckytintinnz/multi-server
  - docker push luckytintinnz/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-southeast-2-349859778146
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

  